# Generated by Django 4.1.7 on 2023-04-25 00:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='event/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=32, verbose_name='Имя')),
                ('pastname', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Отчество')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='person/', verbose_name='Аватар')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_death', models.DateField(verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='EventToPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='Событие')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Персон')),
            ],
            options={
                'verbose_name': 'Событие к персоне',
                'verbose_name_plural': 'События к персонам',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='persons',
            field=models.ManyToManyField(to='core.person', verbose_name='Персоны'),
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(to='core.type', verbose_name='Типы'),
        ),
    ]
