# Generated by Django 4.0.4 on 2023-04-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='persons',
        ),
    ]
