# Generated by Django 4.0.4 on 2023-04-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='wallpaper',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='type/', verbose_name='Обложка'),
        ),
    ]
