# Generated by Django 4.0.4 on 2023-04-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
